### ISSUE TITLE
Multilinguisme

### ISSUE THREAD

**Issue by notabene** [astranchet/design-accessible#22]
Salut et merci pour le site 👍 

Petit bug : il manque les attributs de langue sur les segments qui ne sont pas en français. J'aurais bien voulu faire une PR mais je n'ai pas encore exploré tout le repo, donc je pose ça ici pour qu'on ne l'oublie pas et je peux aider si besoin (mais pas aujourd'hui) 😉 .

## Descriptif complet

**Cas d'usage :** un utilisateur avec un lecteur d'écran entend avec le moteur phonologique français les segments dans d'autres langues
**Étapes pour reproduire :** lancer un lecteur d'écran, parcourir la page https://design-accessible.fr/checklist par exemple, constater que l'anglais n'est pas prononcé correctement
**Corrections :** ajouter des attributs de `lang`

## Exemple

Avant :
```html
<a href="https://www.plainlanguage.gov/guidelines/design" hreflang="en">Design for reading</a>
```

Après :
```html
<a href="https://www.plainlanguage.gov/guidelines/design" hreflang="en" lang="en">Design for reading</a>
```

**Comment by astranchet** [comment]
Merci pour ta PR très claire ! Il se trouve que j'avais fait quelques recherches pour savoir quel(s) attribut(s) mettre. Je n'ai pas du les pousser assez ou bien j'avais mal compris 😅.

La bonne nouvelle, c'est je vais pouvoir le corriger facilement (j'ai étendu le tag 'link' de Kirby pour ajouter hreflang, ça va aller vite de mettre 2 attributs plutôt qu'un)

**Comment by notabene** [comment]
@astranchet ça vaut aussi pour les contenus un peu partout, mais je ne sais pas trop quel formalisme tu veux adopter sans mettre plein de HTML dans ton Markdown.

À ta disposition pour participer, voire le faire _in extenso_ pour une première passe, mais je ne veux pas mettre le bazar donc je fais comme tu me dis de faire 🙂

**Comment by astranchet** [comment]
@notabene par exemple, quand le titre est en anglais, je devrais mettre `<h3 lang="en">$titre de la ressource</h3>` ?

**Comment by astranchet** [comment]
@notabene j'ai mis des exemples de code généré dans la PR, tu peux me dire si ça te paraît bien ?

**Comment by notabene** [comment]
@astranchet ça me semble bien oui, merci !

Pour les pages de contenus statiques, je peux prendre en charge, c'est tout les `*.txt` sous `content` ?

(Mais comme c'est du MD, je pense qu'on ne fera pas l'économie d'un peu de marquage HTML.)

**Comment by astranchet** [comment]
@notabene bien vu, il faut refaire une passe sur les pages statiques (oui, tu les bien repérés). Mais pas besoin de marquage, les liens sont gérés par un `kirbytag`, il faut corriger : 
`(link: https://webaim.org/projects/million/ text: The WebAIM Million)`
en 
`(link: https://webaim.org/projects/million/ text: The WebAIM Million hreflang: en)`

Mais ne t'embête pas, je vais le faire :)

**Comment by notabene** [comment]
> Mais ne t'embête pas, je vais le faire :)

Cœur avec les doigts 😄

**Comment by astranchet** [comment]
@notabene non vraiment, merci à toi de prendre le temps de m'expliquer :)

En tout cas, c'est corrigé/déployé normalement maintenant !

**Comment by notabene** [comment]
Ah bin et la section « Pour aller plus loin » alors dis donc ? 😉

**Comment by astranchet** [comment]
Quand y en a plus, y en a encore 🤐

**Comment by notabene** [comment]
😄 
(c'est pour ça que ça m'intimidait de te demander tout ça sans y mettre la main à la patte)
