### ISSUE TITLE
#a11y - label implicite + erreur d'imbrication

### ISSUE THREAD

**Issue by luce-carevic** [astranchet/design-accessible#24]
Page concernée : https://design-accessible.fr/checklist

Le RGAA n'autorise pas l'emploi d'un label implicite.
Par ailleurs, la spec HTML n'autorise pas l'imbrication d'un hx dans un label.

<label>
        <input type="checkbox" id="faciliter-la-comprehension-rapide-d-une-page">
        <span class="checklist__item__checkmark"></span>
        <h4 class="checklist__item__title">Faciliter la compréhension rapide d'une page</h4>
</label>

**Comment by astranchet** [comment]
Merci pour l'issue ! Cet endroit m'avait déjà donné par mal de fil à retordre et je n'en ai pas fini 😅. Mais je vais y arriver !

**Comment by astranchet** [comment]
Corrigé par @skyounet dans le commit 44685ccc3dc5eb4f1fef5055f4ddbbdc89a9fd27
