### ISSUE TITLE
#a11y - Contraste insuffisant [en]

### ISSUE THREAD

**Issue by luce-carevic** [astranchet/design-accessible#25]
https://design-accessible.fr/checklist

Le gris de l'indication de langue [en] n'est pas suffisamment contrasté.

**Comment by astranchet** [comment]
Merci de ton retour @llune. 
Je peux corriger ce contraste mais il reste que cette indication est peu accessible car elle est générée par du CSS : 
```
  a[hreflang]::after {
      content: "\0000a0[" attr(hreflang) "]";
  }
```
Est-ce que ça peut causer d'autres problèmes d'accessibilité ?

**Comment by notabene** [comment]
> Est-ce que ça peut causer d'autres problèmes d'accessibilité ?

Avis personnel : je trouve moche le « [en] » qui n'est lisible que de nous autres les geeks, je l'utilise de moins en moins.

Il y aurait deux approches, pour moi : 

* soit on ne l'indique pas et on compte sur le fait que les personnes qui lisent vont comprendre (je clique, ah zut, _back_), mais c'es pas super accessible comme idée
* soit on l'indique plus explicitement via CSS (voir ci-dessous) mais ça peut être laborieux (et sans réelle garantie que le contenu généré en CSS soit lu par le lecteur d'écran)
* soit on se sert du back pour le faire proprement mais là encore c'est un peu laborieux

```css
  a[hreflang^="en"]::after {
      content: " (en anglais)";
  }
```

Bref voilà, je ne saurais pas quoi te recommander, chez moi le `hreflang` vient souvent après un `blockquote` pour dire d'où vient ma source, donc je ne le rends pas visible, mais je jette en l'air pour t'aider à avoir tous les tenants et aboutissants.
