### ISSUE TITLE
Selection du texte invisible

### ISSUE THREAD

**Issue by yaf** [astranchet/design-accessible#33]
Quand je sélectionne le texte « Ressources pour concevoir des services utiles et utilisables pour toutes et tous » dans la zone verte de titre (c'est le sous-titre ?), aucun élément visuel me permet de savoir si je l'ai sélectionné ou pas.

Est-ce que c'est voulu parce que c'est une pratique d'accessibilité ? Je suis vraiment très novice en la matière du coup je me trompe peut-être ?

**Comment by astranchet** [comment]
Non, c'est bien un bug CSS : j'ai appliqué une règle sur body, et donc sur le header, ça fait vert sur vert. Oups ! Merci du retour !

**Comment by astranchet** [comment]
Corrigé par le commit b4df1461eb24f93cb39456246d97e5d92e559f1c
