### ISSUE TITLE
Buttons-like link fully clickable?

### ISSUE THREAD

**Issue by davidbgk** [astranchet/design-accessible#38]
I think it would be easier for users to have fully clickable buttons on `tags__item > a`, I would remove the padding to the `li` and add it to the `a` element to fix that. For instance on that page:

<img width="1054" alt="Capture d’écran, le 2021-05-31 à 12 09 46" src="https://user-images.githubusercontent.com/3556/120219487-50249100-c209-11eb-98d2-08f1f2481482.png">

If you are not right on the label of the button it would not be possible to click on the remaining parts of the button.

**Comment by astranchet** [comment]
Merci du retour : "proposer des larges zones de touch", c'est pourtant dans toutes les recommandations de sites accessibles ! Je me note de le corriger

**Comment by davidbgk** [comment]
Super, merci ! Quelle rapidité :)

**Comment by astranchet** [comment]
Je préférais pas m'avancer avant d'avoir essayé mais ça va, je sais encore corriger ce genre de truc en css :D
