### ISSUE TITLE
Personas jeune papa & 78 ans

### ISSUE THREAD

**Issue by luce-carevic** [astranchet/design-accessible#39]
Bonsoir,

Félicitation pour la naissance de ce projet, je ne pense pas l'avoir encore dit :)

Sans chercher le débat sur ce sujet, car je n'ai pas le temps ni l'énergie pour en discuter, je trouve qu'il est dommageable de citer des personas de personnes valides.

Le persona du jeune papa ne me semble pas approprié. Ce n'est pas une situation de handicap.

Dans la même veine, avoir 78 ans n'est pas en soi une situation de handicap.
Ce n'est pas le fait que Marcel a 78 ans qui lui pose des problèmes, mais le fait qu'il soit devenu malvoyant sur le tard.

**Comment by astranchet** [comment]
Hello @llune, merci pour ton commentaire très précieux sur le fond :). Figure toi que je me suis longtemps posée la question, sans réussir à trancher (c'est l'inconvénient de bosser seule, on manque parfois de recul). 

Je vais réfléchir à comment améliorer/changer les textes pour : 
- le jeune papa : je me suis longuement demandée si les situations de handicaps dites "de situation" méritaient leur place.
- la personne âgée et ses multiples handicaps.

Et au passage, je te partages d'autres interrogations que j'ai eu pendant la rédaction de cette page. J'ai pris une décision, mais était-ce la bonne ? Si jamais tu as l'envie de me donner ton avis éclairé, ça m'intéresse !

1. En titrant les cartes avec "Solène est aveugle de naissance.", je réduis une personne (dont le nom a été changé parfois, ou fausse dans certains cas) à son handicap. D'un point de vue hiérarchie de l'information, c'était plus simple que de mettre en avant ce que ça peut changer de son usage du web ("Elle est habituée des technologies et maîtrise les lecteurs d'écrans de son ordinateur et de son smartphone.") ; mais ça me gène et je ne suis pas entièrement satisfaite de ça.
2. L'objectif de cette galerie de "mini-personas" était de représenter la diversité des personnes. Mais cela est évidemment vain, cette liste ne saura jamais être exhaustive. Devrais-je le mentionner plus explicitement ?
3. J'ai choisi de représenter "un peu de chaque" (les grandes familles : visuels/cognitifs/... et le côté temporaire/permanent et même situationnel, sur lequel tu réagis) au détriment de la "réalité statistique" (il y a beaucoup plus de personnes malentendantes qu'avec des troubles cognitifs par exemple). Était-ce un choix pertinent ? (Je suis partie du principe que oui, car justement, si on parle de chiffres, ça va vite de dire "bah c'est minoritaire, ne nous en occupons pas) (et aussi parce que je galérais à avoir tous les chiffres que je cherchais haha).

Bref, merci encore pour ton commentaire très précieux sur le fond :) Je vais prendre le temps de réfléchir à comment améliorer ça.

**Comment by astranchet** [comment]
J'ai reformulé ces 2 personas dans le commit 4d6c58c8db97a47736e750aa17c99f15b4c2abcb (et corrigé un 3ème où j'avais mixé `dyspraxique` et `disphasique` pour inventer le terme `dysphrasique` 🤦‍♀️)

**Comment by luce-carevic** [comment]
De rien pour le retour. Désolée, j'ai très peu d'énergie en ce moment, donc pas beaucoup le temps de bien répondre. 

C'est une question complexe et je trouve que la correction enlève déjà le problème de mettre en avant des personnes valides ce qui est cool :)

**Comment by astranchet** [comment]
Prends soin de toi :)
