### ISSUE TITLE
Page accessibilité - propositions d'amélioration

### ISSUE THREAD

**Issue by luce-carevic** [astranchet/design-accessible#46]
>Le site Design Accessible n’a pas été audité par des experts. Il est donc considéré comme non conforme avec le RGAA 4.1 (Hey oui, c’est le jeu 🤷). 

Je pense que la phrase actuelle peut être mal comprise et laisser comprendre que la législation actuelle qui considère qu'un site non audité est réputé non conforme est absurde / trop sévère (alors que c'est plutôt à mon sens incitatif).

Je conseille de reformuler ainsi (adaptable évidemment) : 

>Le site Design Accessible n’a pas fait l’objet d’un audit RGAA 4.1. Il est donc impossible en l’état d’en évaluer la conformité avec le référentiel.

Je te conseillerai également de rajouter une phrase qui invite à remonter les éventuels problèmes rencontrés avec un moyen de contact (comme c'est demandé par le RGAA dans les déclarations d'accessibilité).

**Comment by astranchet** [comment]
Effectivement, mon "c'est aburde" pourrait être mal compris .

Très bonne idée aussi pour le moyen de contact 👍.
